[package]
name = "unytctl"
version = "0.3.1"
edition = "2024"

[[bin]]
name = "unytctl"
path = "src/main.rs"

[dependencies]
# Holochain deps
holochain_client = { version = "0.9", features = ["lair_signing"] }
holo_hash = "0.7"
holochain_types = "0.7"
hc_seed_bundle = "0.7"
lair_keystore_api = "0.7"

# Other deps
anyhow = "1.0"
base64 = "0.23"
clap = "4.6"
hex = "0.4"
reqwest = { version = "0.13", features = ["json"] }
rpassword = "7.5"
serde = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "2.0"
tokio = { version = "1.53", features = ["macros", "rt-multi-thread"] }
url = "2.5"
yaml_serde = "0.10"
zeroize = "1.9.0"

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
